In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier

# -----------------------------
# 1) 데이터 준비
# -----------------------------
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/weather.csv")
df

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0     11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3   
1     11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7   
2     11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3   
3     11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1   
4     11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6   
..          ...       ...      ...      ...       ...          ...       ...   
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1   
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7   
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3   
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1   
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6   

    WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0            NW           30.0         SW  ...          29       1019.7   
1           ENE           39.0          E  ...          36       1012.4   
2            NW           85.0          N  ...          69       1009.5   
3            NW           54.0        WNW  ...          56       1005.5   
4           SSE           50.0        SSE  ...          49       1018.3   
..          ...            ...        ...  ...         ...          ...   
361         NNW           76.0        SSE  ...          15       1016.1   
362           N           48.0        NNW  ...          22       1020.0   
363         ESE           43.0        ENE  ...          47       1024.0   
364          NW           46.0        SSW  ...          39       1021.0   
365          NW           78.0         NW  ...          13       1009.6   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0         1015.0         7         7     14.4     23.6         No      3.6   
1         1008.4         5         3     17.5     25.7        Yes      3.6   
2         1007.2         8         7     15.4     20.2        Yes     39.8   
3         1007.0         2         7     13.5     14.1        Yes      2.8   
4         1018.5         7         7     11.1     15.4        Yes      0.0   
..           ...       ...       ...      ...      ...        ...      ...   
361       1010.8         1         3     20.4     30.0         No      0.0   
362       1016.9         0         1     17.2     28.2         No      0.0   
363       1022.8         3         2     14.5     18.3         No      0.0   
364       1016.2         6         7     15.8     25.9         No      0.0   
365       1009.2         1         1     23.8     28.6         No      0.0   

     RainTomorrow  
0             Yes  
1             Yes  
2             Yes  
3             Yes  
4              No  
..            ...  
361            No  
362            No  
363            No  
364            No  
365            No  

[366 rows x 24 columns]

In [ ]:
df.isnull().sum()

Date             0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         3
WindGustSpeed    2
WindSpeed9am     7
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

Date             0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [ ]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     290
Yes     64
Name: count, dtype: int64

In [38]:
le = LabelEncoder()

for col in df.columns :
  df[col] = le.fit_transform(df[col]);

df

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      62         0       98      120         0           15        45   
1      73         0      148      139        16           20        77   
2      84         0      145      115        16           27        24   
3      86         0      143       48        46           34        71   
4      87         0       94       52        13           26        86   
..    ...       ...      ...      ...       ...          ...       ...   
361    50         0      108      164         0           36       101   
362    51         0       89      150         0           51       106   
363    52         0      135       87         0           40        38   
364    54         0      135      139         0           23        52   
365    55         0      133      162         0           28       105   

     WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity3pm  Pressure9am  \
0              7              8          12  ...           15           94   
1              1             12           0  ...           22           38   
2              7             33           3  ...           55           21   
3              7             20          14  ...           42            7   
4             10             18          10  ...           35           85   
..           ...            ...         ...  ...          ...          ...   
361            6             29          10  ...            2           65   
362            3             17           6  ...            8           97   
363            2             14           1  ...           33          133   
364            7             16          11  ...           25          105   
365            7             30           7  ...            0           22   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0             84         7         7      105      136          0       16   
1             28         5         3      133      152          1       16   
2             23         8         7      113      106          1       46   
3             22         2         7       98       53          1       13   
4            115         7         7       78       64          1        0   
..           ...       ...       ...      ...      ...        ...      ...   
361           47         1         3      158      177          0        0   
362          100         0         1      130      169          0        0   
363          151         3         2      106       88          0        0   
364           93         6         7      117      153          0        0   
365           35         1         1      175      172          0        0   

     RainTomorrow  
0               1  
1               1  
2               1  
3               1  
4               0  
..            ...  
361             0  
362             0  
363             0  
364             0  
365             0  

[366 rows x 24 columns]

In [ ]:
X = df.drop(columns=["RainTomorrow"])
y = df["RainTomorrow"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
X

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0      61       95      118         0           15        45              8   
1      72      144      137        16           20        77             12   
2      83      141      113        16           27        24             33   
3      85      139       47        45           34        71             20   
4      86       91       51        13           26        86             18   
..    ...      ...      ...       ...          ...       ...            ...   
361    49      105      160         0           36       101             29   
362    50       86      148         0           51       106             17   
363    51      131       85         0           40        38             14   
364    53      131      137         0           23        52             16   
365    54      129      158         0           28       105             30   

     WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0               3            10           29           15           93   
1               2             8           41           22           37   
2               3             2           43           55           20   
3              16            12           23           42            7   
4              11            14           29           35           84   
..            ...           ...          ...          ...          ...   
361             4            23            1            2           64   
362             1             9            6            8           96   
363             6             4           24           33          132   
364             3            14           30           25          104   
365            17            18            4            0           21   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  
0             83         7         7      102      135          0  
1             27         5         3      130      151          1  
2             22         8         7      110      105          1  
3             21         2         7       95       53          1  
4            114         7         7       75       63          1  
..           ...       ...       ...      ...      ...        ...  
361           46         1         3      155      175          0  
362           99         0         1      127      167          0  
363          150         3         2      103       87          0  
364           92         6         7      114      152          0  
365           34         1         1      172      170          0  

[354 rows x 18 columns]

In [ ]:
y

0      1
1      1
2      1
3      1
4      0
      ..
361    0
362    0
363    0
364    0
365    0
Name: RainTomorrow, Length: 354, dtype: int64

In [ ]:
# -----------------------------
# 2) 모델 구성
# -----------------------------
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(n_estimators=200, random_state=42)
lr = LogisticRegression(max_iter=2000)

knn = KNeighborsClassifier(n_neighbors=50)

In [ ]:
# -----------------------------
# 3) 모델 학습
# -----------------------------
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)
lr.fit(X_train, y_train)

knn.fit(X_train, y_train)

In [39]:
# -----------------------------
# 4) 모델 평가
# -----------------------------
dt_acc = accuracy_score(y_test, dt.predict(X_test))
rf_acc = accuracy_score(y_test, rf.predict(X_test))
lr_acc = accuracy_score(y_test, lr.predict(X_test))

knn_acc = accuracy_score(y_test, knn.predict(X_test))

print("=== DT Test Accuracy ===")
print(f"Decision Tree : {dt_acc:.4f}")
print(confusion_matrix(y_test,dt.predict(X_test)))

print("=== RF Test Accuracy ===")
print(f"Random Forest : {rf_acc:.4f}")
print(confusion_matrix(y_test,rf.predict(X_test)))

print("=== LR Test Accuracy ===")
print(f"Logistic Reg. : {lr_acc:.4f}")
print(confusion_matrix(y_test,lr.predict(X_test)))

print(f"KNN : {knn_acc:.4f}")

=== DT Test Accuracy ===
Decision Tree : 0.8592
[[54  4]
 [ 6  7]]
=== RF Test Accuracy ===
Random Forest : 0.8451
[[55  3]
 [ 8  5]]
=== LR Test Accuracy ===
Logistic Reg. : 0.8732
[[54  4]
 [ 5  8]]
KNN : 0.8169
